### ISSUE TITLE
ImageNet tensorflow_datasets setup

### ISSUE THREAD

**Issue by martinmamql** [google-research/simclr#32]
Dear Ting,

Thank you so much for providing this great codebase for the community!

When I tried to train simclr on ImageNet using TPU, I got different errors when the code tried to read the `ILSVRC2012_img_train.tar` and `ILSVRC2012_img_val.tar` (I have downloaded those files). Following [docs](https://www.tensorflow.org/datasets/catalog/imagenet2012) will trigger different errors. May I gently ask on TPU cloud how did you set up the ImageNet TensorFlow dataset properly given that the data is downloaded?

If you would like me to provide the error information, I will post it :)

Thank you so much!

**Comment by chentingpc** [comment]
Did you put the downloaded files in the right folder where tfds is pointed? I remembered that was an issue that I tried several options to figure out. You can post the error msg here and I can try to help, but I am not sure if I can help much. An alternative is to ask on https://github.com/tensorflow/datasets/, since SimCLR uses tfds in a standard way.

**Comment by martinmamql** [comment]
I see! Thank you so much! I will try to work around tfds, if not I will open issues on tensorflow/datasets. Appreciate your reply and please feel free to close this issue:)

**Comment by chentingpc** [comment]
I am closing it for now, but feel free to reopen if you have further questions:)
