### ISSUE TITLE
Difference between train_then_eval and eval

### ISSUE THREAD

**Issue by tarunn2799** [google-research/simclr#78]
I'm looking to perform Linear evaluation by freezing the encoder, as well as finetune the whole system,  on Stanford Cars using the Imagenet models given in the repo for SimCLR v1. 
What's the difference between train_then_eval and eval? Which one should I use for my test case?

Also, any particular reason why you guys chose to write the code in TF v1? Would love tips on how I can convert the given ResNet50 hub files compatible to v2.

**Comment by chentingpc** [comment]
Given that you need to finetune the pretrained net, you should use train_then_eval instead of eval, which simply evaluate existing net without finetuning. 

Stay tuned for TF v2 implementation which is a WIP. In the meantime, there're some non-official implementations (see the bottom part of readme page).

**Comment by tarunn2799** [comment]
Thank you!!
