### ISSUE TITLE
Effect of augmentation on the distillation/self-training task

### ISSUE THREAD

**Issue by sayakpaul** [google-research/simclr#81]
Hey @chentingpc. Thanks for including the distillation notebook!

I was wondering what's the effect of using the same SimCLR augmentation policies on the downstream dataset. Also, did you try any other optimizers (other than LARS) for these relatively smaller datasets like Flower?

**Comment by chentingpc** [comment]
We didn't use SimCLR augmentation when transferring to downstream dataset. But we do fine-tune on ImageNet, and SimCLR augmentation doesn't have a significant effect there as it is already used during pretraining. If you choose to use SimCLR augmentation for supervised learning, you should tune the strength in order to get best performance.

We only used SGD/momentum for transfer experiments.

**Comment by sayakpaul** [comment]
Much helpful, @chentingpc. I was wondering why the distillation and self-training Colab Notebook follows other approaches like using LARS, SimCLR like augmentations, and so on.

**Comment by chentingpc** [comment]
It is standard augmentation (not SimCLR augmentation) with random crop & horizontal flip (since the `color_distort` is set to False).

LARS vs SGD here is a somewhat arbitrary choice. It should perform the same with either SGD or LARS (it is basically like supervised learning at distillation stage).

**Comment by sayakpaul** [comment]
Fair points. Thank you.
